spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: false
  
  h2:
    console:
      enabled: true
  
  redis:
    host: localhost
    port: 6379

  sql:
    init:
      mode: never

server:
  port: 8080

app:
  name: School Information Management System (SIM)
  version: 1.0.0
  description: Backend API for the School Information Management System
  cors:
    allowed-origins: "http://localhost:8080,http://localhost:3000,http://127.0.0.1:8080,http://127.0.0.1:3000"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
    allowed-headers: "*"
    allow-credentials: true